### PR TITLE
PLAT-10366: Added generated API

### PR DESCRIPTION
**Pull request by symphony-elias**
### Ticket
PLAT-10366

### Description
Added generated API from swagger specs, namely:
- https://github.com/symphonyoss/symphony-api-spec/blob/master/agent/agent-api-public.yaml
- https://github.com/symphonyoss/symphony-api-spec/blob/master/authenticator/authenticator-api-public.yaml
- https://github.com/symphonyoss/symphony-api-spec/blob/master/login/login-api-public.yaml
- https://github.com/symphonyoss/symphony-api-spec/blob/master/pod/pod-api-public-deprecated.yaml

Generate api and models were put in separate python packages because of clashing tags across yaml files making some python modules to be overwritten.

Updated circle ci file to trigger snyk scan on 2.0 branch

### Checklist
- [x] Referenced a ticket in the PR title and in the corresponding section
- [x] Filled properly the description and dependencies, if any
- [NA] Unit tests updated or added
- [NA] Docstrings added or updated
- [x] Updated the documentation in [docs folder](../docs)

### CODE REVIEW

**Review by symphony-youness — APPROVED** [review]
LGTM

**Comment by symphony-hong** [comment]
I have a small question is that do we need to commit also the template since we decided to commit all the generated code? it's somehow redundant, isn't it?

**Comment by symphony-elias** [comment]
> I have a small question is that do we need to commit also the template since we decided to commit all the generated code? it's somehow redundant, isn't it?

Yes but this is just in case we want to regenerate then files when swagger specs change. One never knows and I prefer to keep it.

**Review by symphony-hong — APPROVED** [review]
LGTM

**Review by thibauult — APPROVED** [review]

**Review by symphony-youri — APPROVED** [review]

**Pull request merged**
